[workspace]
members = ["packages/*", "tools/*", "examples/*"]
default-members = ["packages/*"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[profile.bench]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3

[patch.crates-io]
gloo = { git = "https://github.com/langyo/gloo", branch = "wasi-fix" }
prokio = { git = "https://github.com/langyo/prokio", branch = "wasi-fix" }
