[target.'cfg(all(target_arch = "wasm32", not(feature = "wasi")))']
runner = 'wasm-bindgen-test-runner'

# This section needs to be last.
# GitHub Actions modifies this section.
[unstable]
doctest-xcompile = true
