name: Main Checks on WASI

on:
  pull_request:
    paths:
      - '.github/workflows/main-checks-wasi.yml'
      - 'ci/**'
      - 'packages/**/*'
      - 'Cargo.toml'
      - 'Cargo.lock'
  push:
    branches: [master]

jobs:
  unit_tests:
    name: Unit Tests on ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - 1.64.0
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-wasi

      - name: Install wasmtime
        run: |
          wget https://github.com/bytecodealliance/wasmtime/releases/download/v15.0.1/wasmtime-v15.0.1-x86_64-linux.tar.xz
          tar xf wasmtime-v15.0.1-x86_64-linux.tar.xz
          mv wasmtime-v15.0.1-x86_64-linux/wasmtime ~/wasmtime
          rm -rf wasmtime-v15.0.1-x86_64-linux.tar.xz wasmtime-v15.0.1-x86_64-linux
          chmod +x ~/wasmtime

      - uses: Swatinem/rust-cache@v2

      - name: Run WASI tests for yew
        run: |
          RUST_LOG=info
          cargo test --features ssr --target wasm32-wasi -p yew --no-run 2>&1 |\
            grep -o "target/wasm32-wasi/debug/deps/[^ ]*\.wasm" |\
            xargs -I {} ~/wasmtime -W unknown-imports-trap=y {}

      - name: Run WASI tests for yew-router
        run: |
          cargo test --features ssr --target wasm32-wasi -p yew-router --no-run 2>&1 |\
            grep -o "target/wasm32-wasi/debug/deps/[^ ]*\.wasm" |\
            xargs -I {} ~/wasmtime -W unknown-imports-trap=y {}

  example-runnable-tests-on-wasi:
    name: Example Runnable Tests on WASI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - wasi_ssr_module
        toolchain:
          - 1.64.0
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-wasi

      - name: Install wasmtime
        run: |
          wget https://github.com/bytecodealliance/wasmtime/releases/download/v15.0.1/wasmtime-v15.0.1-x86_64-linux.tar.xz
          tar xf wasmtime-v15.0.1-x86_64-linux.tar.xz
          mv wasmtime-v15.0.1-x86_64-linux/wasmtime ~/wasmtime
          rm -rf wasmtime-v15.0.1-x86_64-linux.tar.xz wasmtime-v15.0.1-x86_64-linux
          chmod +x ~/wasmtime

      - uses: Swatinem/rust-cache@v2

      - name: Build and run ${{ matrix.package }}
        run: |
          cargo build --target wasm32-wasi -p ${{ matrix.package }}
          ~/wasmtime -W unknown-imports-trap=y target/wasm32-wasi/debug/${{ matrix.package }}.wasm
